// GENERATED CODE - DO NOT MODIFY BY HAND

// **************************************************************************
// Total assets: 1.
// Generated by https://pub.dev/packages/assets_gen.
// **************************************************************************
class Assets {
  static const String package = 'settings';

  static const String assets_images_profile_bg_webp = 'assets/images/profile_bg.webp';
  static const String settings$assets_images_profile_bg_webp = 'packages/settings/assets/images/profile_bg.webp';
}
