// GENERATED CODE - DO NOT MODIFY BY HAND

// **************************************************************************
// Total assets: 3.
// Generated by https://pub.dev/packages/assets_gen.
// **************************************************************************
class Assets {
  static const String package = 'common';

  static const String assets_images_star_dark_webp = 'assets/images/star_dark.webp';
  static const String common$assets_images_star_dark_webp = 'packages/common/assets/images/star_dark.webp';

  static const String assets_images_star_light_webp = 'assets/images/star_light.webp';
  static const String common$assets_images_star_light_webp = 'packages/common/assets/images/star_light.webp';

  static const String assets_images_tab_indicator_webp = 'assets/images/tab_indicator.webp';
  static const String common$assets_images_tab_indicator_webp = 'packages/common/assets/images/tab_indicator.webp';
}
