// GENERATED CODE - DO NOT MODIFY BY HAND

// **************************************************************************
// Total assets: 4.
// Generated by https://pub.dev/packages/assets_gen.
// **************************************************************************
class Assets {
  static const String package = 'projectf';

  static const String assets_images_tab_discovery_webp = 'assets/images/tab_discovery.webp';
  static const String projectf$assets_images_tab_discovery_webp = 'packages/projectf/assets/images/tab_discovery.webp';

  static const String assets_images_tab_main_webp = 'assets/images/tab_main.webp';
  static const String projectf$assets_images_tab_main_webp = 'packages/projectf/assets/images/tab_main.webp';

  static const String assets_images_tab_message_webp = 'assets/images/tab_message.webp';
  static const String projectf$assets_images_tab_message_webp = 'packages/projectf/assets/images/tab_message.webp';

  static const String assets_images_tab_settings_webp = 'assets/images/tab_settings.webp';
  static const String projectf$assets_images_tab_settings_webp = 'packages/projectf/assets/images/tab_settings.webp';
}
