name: common
description: A new Flutter project.
version: 0.0.1
homepage:

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

  intl: 0.17.0
  dog: 1.4.0
  dio: ^5.3.3
  get: ^4.6.5


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  assets_gen: 1.1.2

flutter:
  uses-material-design: true

  assets:
    - assets/images/
