name: main
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  common:
    path: ../../baseModule/common
  get: ^4.6.5
  cupertino_icons: ^1.0.2
  json_annotation: ^4.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  build_runner: ^2.0.0
  json_serializable: ^6.1.1
  assets_gen: 1.1.2

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  module:
    androidX: true
    androidPackage: com.jinn.main
    iosBundleIdentifier: com.jinn.main
