name: settings
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  common:
    path: ../../baseModule/common

  cupertino_icons: ^1.0.2
  get: ^4.6.5
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  assets_gen: 1.1.2

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  module:
    androidX: true
    androidPackage: com.jinn.settings
    iosBundleIdentifier: com.jinn.settings
